version: 

models:
  - name: stg_aeroplanes
    columns:
      - name: airplane_id
        tests:
          - not_null
          - unique

  - name: stg_customer_group
    columns:
      - name: customer_group_id
        tests:
          - not_null
          - unique

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

  - name: stg_trips
    columns:
      - name: trip_id
        tests:
          - not_null
          - unique

